### ISSUE TITLE
How do I use a BearerTokenFile ?

### ISSUE THREAD

**Issue by oleborne** [wavefrontHQ/observability-for-kubernetes#370]
Hello, 

In the configuration for a Prometheus Source, I can see a [ClientConfig property (httpConfig)](https://github.com/wavefrontHQ/observability-for-kubernetes/blob/351e6aa688e3f453204f239a1d4c1c529f6f257e/collector/internal/configuration/config.go#L226C35-L226C35) which is also [mentioned in the documentation](https://github.com/wavefrontHQ/observability-for-kubernetes/blob/351e6aa688e3f453204f239a1d4c1c529f6f257e/collector/internal/configuration/config.go#L226C35-L226C35).

There I can see a [``BearerTokenFile`` property](https://github.com/wavefrontHQ/observability-for-kubernetes/blob/351e6aa688e3f453204f239a1d4c1c529f6f257e/collector/internal/httputil/configs.go#L19). The content of that file would be [read every time a request is performed](https://github.com/wavefrontHQ/observability-for-kubernetes/blob/351e6aa688e3f453204f239a1d4c1c529f6f257e/collector/internal/httputil/client.go#L82) and [added as a bearer token](https://github.com/wavefrontHQ/observability-for-kubernetes/blob/351e6aa688e3f453204f239a1d4c1c529f6f257e/collector/internal/httputil/client.go#L89).

I was thinking about having a Secret containing a bearer token and a CronJob would ensure that the content of that secret is always fresh and valid. However, I'm stuck on how I would mount such secret as a file in the Collector pod.

I don't see any option where I can mount an arbitrary volume into the pod. There's [only specific logic and no options for customisation](https://github.com/wavefrontHQ/observability-for-kubernetes/blob/351e6aa688e3f453204f239a1d4c1c529f6f257e/operator/deploy/internal/collector/3-wavefront-collector-daemonset.yaml#L98-L114) as far as I can understand.

Thanks for your help for moving forward.

**Comment by johncornish** [comment]
Hi @oleborne , we have a discussion planned around this tomorrow morning and will update then.

**Comment by johncornish** [comment]
Hi @oleborne , would a runtime plugin secret solve your problem? You could create or update a secret with the cron job with the bearer token, for example:

```
apiVersion: v1
kind: Secret
metadata:
  name: apiserver-config
  namespace: observability-system
  annotations:
    wavefront.com/discovery-config: 'true'
stringData:
  collector.yaml: |
    plugins:
      # apiserver
      - name: apiserver
        type: prometheus
        selectors:
          # set resource type to service
          resourceType: service
          # modify service labels as relevant
          labels:
            component:
              - apiserver
            provider:
              - kubernetes
        prefix: kube.apiserver.
        scheme: https
        port: 443
        path: /metrics
        conf: |
          bearer_token: <some_token>
          tls_config:
            ca_file: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
            insecure_skip_verify: true
```
