### ISSUE TITLE
Setting proxy name

### ISSUE THREAD

**Issue by sergio-moreira-everi** [wavefrontHQ/observability-for-kubernetes#489]
I noticed that the default behavior in wavefront is the pod name is taken as the proxy name. Is there a way to set a static proxy name in the wavefront.yaml similar to the `proxyname` variable in wavefront.conf? 

Something like this maybe would be good:

```yaml
spec:
  .....
  dataExport:
    wavefrontProxy:
      enable: true
      name: my-custom-proxy-name
```

**Comment by Jyuqi** [comment]
Hello @sergio-moreira-everi, it is also possible to specify options as proxy command line parameters in the `dataExport.wavefrontProxy.args` field. For example:

```
spec:
  .....
  dataExport:
    wavefrontProxy:
      enable: true
      args: >
        --proxyname=my-custom-proxy-name
```
